# Site settings
title: DojoCon Japan 2016 - The more dojos, the more cool coders. -
description: あなたも子供がプログラミングで創りたいものをサポートしてみませんか？DojoConは、子供のプログラミングをサポートしてみたいエンジニアや、教育者が集まるカンファレンスです。
url: https://dojocon-japan.github.io
baseurl: ''

entryurl: http://eventregist.com/e/DojoConJapan2016
workshop_entryurl_1: http://eventregist.com/e/Scratch1
workshop_entryurl_2: http://eventregist.com/e/Scratch2
workshop_entryurl_3: http://eventregist.com/e/Scratch3
venueurl: http://www.uchida.co.jp/company/showroom/canvas/osaka/

sponsorform_url: https://docs.google.com/forms/d/1mXQ45DxPV9le-_cGRSXaMbF5eSHDt1ipM_duBuUwwJg/viewform
contactform_url: https://docs.google.com/forms/d/1jOp-orD2XQovdp7g3QeJF7wFcp9poNRga_bpnMCYf8Q/viewform

twitter:
  id: DojoConJapan
  hashtag: DojoConJP

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - npm-debug.log
  - README.md
  - LICENSE

compress_html:
  clippings: all
  comments: all
  endings: all
  # ignore:
  #   envs: [development]
  # blanklines: true
  # profile: true
  startings: [html, head, body]

url: http://dojocon2016.coderdojo.jp
